dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import welcome

app_name= "dingo"

urlpatterns = [
    path('', welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path('maths/', include('maths.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('sessions/', include("sessions.urls")),
    path('posts/', include("posts.urls")),
]

maths/urls.py
from django.urls import path
from .views import math, add, sub, mul, div,maths_list, math_details,results_list

app_name="maths"

urlpatterns = [
   path('', math),
   path('add/<int:a>/<int:b>', add),
   path('sub/<int:a>/<int:b>', sub),
   path('mul/<int:a>/<int:b>', mul),
   path('div/<int:a>/<int:b>', div),
   path('histories/', maths_list, name="list"),
   path('histories/<int:id>', math_details, name="details"),
   path('results/', results_list, name="results"),
]

maths/models.py
# maths/models.py
from django.db import models


class Math(models.Model):
    # Create your models here.
    class Operations(models.TextChoices):
        ADDING = "add"
        SUBTRACT = "sub"
        MULTIPLICATION = "mul"
        DIVISION = "div"

    operation = models.CharField(max_length=5, choices=Operations.choices)
    a = models.IntegerField()
    b = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    result = models.ForeignKey(
        'maths.Result',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"id:{self.id}, a={self.a}, b={self.b}, op={self.operation}"


class Result(models.Model):
    value = models.FloatField(blank=True, null=True, unique=True)
    error = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        unique=True
    )

    def __str__(self):
        return f"value: {self.value} | error: {self.error}"

    class Meta:
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_value_error_together",
                check=(
                        models.Q(
                            value__isnull=False,
                            error__isnull=True,
                        )
                        | models.Q(
                    value__isnull = True,
                    error__isnull = False,
                )
                ),
            )
        ]

maths/forms.py
from django import forms
from .models import Result

class ResultForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        value = cleaned_data.get('value')
        error = cleaned_data.get('error')

        if all([value, error]):
            raise forms.ValidationError("Podaj tylko jedną z wartości")
        elif not any([value, error]):
            raise forms.ValidationError("Nie podano żadnej wartości!")

    class Meta:
        model = Result
        fields = ["value", "error"]

maths/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render
from .models import Math, Result
from .forms import ResultForm
from django.core.paginator import Paginator


# Create your views here.
def math(request):
    return HttpResponse("Tu będzie matma")


def add(request, a, b):
    wynik = a + b
    c = {"a": a, "b": b, "operacja": "+", "wynik": wynik, "title": "dodawanie"}
    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='add', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operations.html",
        context=c
    )


def sub(request, a, b):
    wynik = a - b
    c = {"a": a, "b": b, "operacja": "-", "wynik": wynik, "title": "odejmowanie"}
    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='sub', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operations.html",
        context=c
    )


def mul(request, a, b):
    wynik = a * b
    c = {"a": a, "b": b, "operacja": "*", "wynik": wynik, "title": "mnożenie"}
    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='mul', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operations.html",
        context=c
    )


def div(request, a, b):
    if int(b) == 0:
        wynik = "Error"
        messages.add_message(request, messages.ERROR, "Dzielenie przez zero!")
        result = Result.objects.get_or_create(error=wynik)[0]
    else:
        wynik = a / int(b)
        result = Result.objects.get_or_create(value=wynik)[0]
    c = {"a": a, "b": b, "operacja": "/", "wynik": wynik, "title": "dzielenie"}

    Math.objects.create(operation='div', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operations.html",
        context=c
    )


def maths_list(request):
    maths = Math.objects.all().order_by('id')
    paginator = Paginator(maths, 5)
    page_number = request.GET.get('page')
    maths = paginator.get_page(page_number)
    return render(
        request=request,
        template_name="maths/list.html",
        context={"maths": maths}
    )


def math_details(request, id):
    math = Math.objects.get(id=id)
    return render(
        request=request,
        template_name="maths/details.html",
        context={"math": math}
    )


def results_list(request):
    if request.method == "POST":
        form = ResultForm(data=request.POST)

        if form.is_valid():
            if form.cleaned_data['error'] == '':
                form.cleaned_data['error'] = None
            Result.objects.get_or_create(**form.cleaned_data)
            messages.add_message(
                request,
                messages.SUCCESS,
                "Utworzono nowy Result!!"
            )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                form.errors['__all__']
            )

    form = ResultForm()
    results = Result.objects.all()
    return render(
        request=request,
        template_name="maths/results.html",
        context={
            "results": results,
            "form": form
        }
    )

maths/templates/maths/details.html
{% extends "maths/main.html" %}

{% load bootstrap4 %}

{% block title %}Maths list{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <table class="table table-bordered">
        <tr>
          <th>Operation</th>
          <td>{{ math.operation }}</td>
        </tr>
        <tr>
          <th>a</th>
          <td>{{ math.a }}</td>
        </tr>
        <tr>
          <th>b</th>
          <td>{{ math.b }}</td>
        </tr>
        <tr>
          <th>Created:</th>
          <td>{{ math.created }}</td>
        </tr>
        <tr>
          <th>Result</th>
          <td>{{ math.result }}</td>
        </tr>
      </table>
      <a href="{% url "maths:list" %}" class="btn btn-primary">Back</a>
    </div>
  </div>
</div>
{% endblock %}

maths/templates/maths/list.html
{% extends "maths/main.html" %}

{% block title %}Maths list{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Maths list</h2>
            <ul class="list-group">
                {% for m in maths %}
                    {# <li><a href="{% url "maths:histories" m.id %}" >{{ m }}</a></li> #}
                    <li class="list-group-item">
                        <a href="{% url "maths:details" m.id %}">{{ m }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

maths/templates/maths/main.html
{% extends 'dingo/main.html' %}
{% block main %}
<body>
<div id="content">

   {% if messages %}
       <ul class="messages">
           {% for message in messages %}
               <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
           {% endfor %}
       </ul>
   {% endif %}
   <div id="inner-content">

       {% block content %}
           To jest blok kodu. W innych szablonach możemy go nadpisać
       {% endblock %}
   </div>
</div>
</body>
{%endblock%}

maths/templates/maths/operations.html
{% extends "maths/main.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
   Wynik operacji {{ a }} {{ operacja }} {{ b }} wynosi {{ wynik }}
{% endblock %}

maths/templates/maths/results.html
{% extends "maths/main.html" %}

{% block title %}Maths list{% endblock %}

{% block content %}
   <ul>
       {% for r in results %}
           <li>{{ r }}</li>
       {% endfor %}
   </ul>

<form method="POST">
   {% csrf_token %}
   {{ form.as_table }}
   <input type="submit" value="go">
</form>



{% endblock %}