dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import welcome

app_name= "dingo"

urlpatterns = [
    path('', welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path('maths/', include('maths.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('sessions/', include("sessions.urls")),
    path('posts/', include("posts.urls")),
]

maths/urls.py
from django.urls import path
from .views import math, add, sub, mul, div,maths_list, math_details,results_list

app_name="maths"

urlpatterns = [
   path('', math),
   path('add/<int:a>/<int:b>', add),
   path('sub/<int:a>/<int:b>', sub),
   path('mul/<int:a>/<int:b>', mul),
   path('div/<int:a>/<int:b>', div),
   path('histories/', maths_list, name="list"),
   path('histories/<int:id>', math_details, name="details"),
   path('results/', results_list, name="results"),
]

portfolio/urls.py
from django.urls import path
from .views import main, me, contact
app_name = "portfolio"
urlpatterns = [
    path('', main, name='main'),
    path('me', me, name='me'),
    path('contact', contact, name='contact'),

]

posts/urls.py
from django.urls import path
from .views import authors_list,posts_list ,post_details ,author_details

app_name = "posts"

urlpatterns = [
    path('authors_list', authors_list,name='authors_list'),
    path('posts_list', posts_list,name='posts_list'),
    path('post_details/<int:pk>/', post_details, name='post_details'),
    path('author_details/<int:author_id>/', author_details, name='author_details'),
]

greetings/templates/greetings/main.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

   {# Load CSS and JavaScript #}
   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}
</head>
<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'portfolio:main' %}">Dingo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'portfolio:main' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'portfolio:contact' %}">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'portfolio:me' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'maths:list' %}">Maths</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:posts_list' %}">Posts</a>
      </li>
    </ul>
  </div>
</nav>
{%block main %}
{%endblock %}
</body>
</html>