dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import welcome

app_name= "dingo"

urlpatterns = [
    path('', welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path('maths/', include('maths.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('sessions/', include("sessions.urls")),
    path('posts/', include("posts.urls")),
]

posts/urls.py
from django.urls import path
from .views import authors_list,posts_list ,post_details ,author_details

app_name = "posts"

urlpatterns = [
    path('authors_list', authors_list,name='authors_list'),
    path('posts_list', posts_list,name='posts_list'),
    path('post_details/<int:pk>/', post_details, name='post_details'),
    path('author_details/<int:author_id>/', author_details, name='author_details'),
]

posts/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator
from django.db import models
from django_extensions.db.models import TimeStampedModel


# Create your models here.
class Post(TimeStampedModel):
    title = models.CharField(max_length=20)
    content = models.TextField(max_length=1024)
    author = models.ForeignKey('posts.Author', on_delete=models.CASCADE)

    def __str__(self):
        return (
            f"Title: {self.title}\n"
            f"Content: {self.content}\n"
            f"Created: {self.created}\n"
            f"Modified: {self.modified}\n"
            f"Author: {self.author}"
        )


class Author(models.Model):
    nick = models.CharField(max_length=15, unique=True)
    bio = models.TextField(blank=True, max_length=1024, validators=[MaxLengthValidator(1024, message="Bio za długie")])
    email = models.EmailField(max_length=30, blank=True, unique=True)


    def __str__(self):
        email_str = f" ({self.email})" if self.email else ""
        bio_str = f" - {self.bio[:50]}..." if self.bio else ""
        return f"{self.nick}{email_str}{bio_str}"

    def save(self, *args, **kwargs):
        self.full_clean()

        super(Author, self).save(*args, **kwargs)

posts/forms.py
from django import forms
from .models import Author, Post


class PostForm(forms.ModelForm):
    author = forms.ModelChoiceField(queryset=Author.objects.all())
    class Meta:
        model = Post
        fields = ['author', 'title', 'content']

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['nick', 'bio', 'email']

posts/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Author, Post
from .forms import AuthorForm,PostForm


# Create your views here.
def authors_list(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authors_list')
    else:
        form = AuthorForm()

    authors = Author.objects.all()
    return render(
        request=request,
        template_name="posts/authors_list.html",
        context={"form": form, "authors": authors, "title": "Authors list"}
    )


def posts_list(request):
    posts = Post.objects.all()
    form = PostForm()
    if request.method == "POST":
        form = PostForm(data=request.POST)
        if form.is_valid():
            form.save()
    return render(
        request=request,
        template_name="posts/posts_list.html",
        context={"form": form, "posts": posts, "title": "Posts list"}
    )


def author_details(request,author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'posts/author_details.html', {'author': author, 'title': 'Author details'})



def post_details(request, pk):
    post = get_object_or_404(Post, pk=pk)

    return render(
        request=request,
        template_name="posts/post_details.html",
        context={"post": post, "title": "Post details"}
    )

posts/templates/posts/author_details.html
{% extends 'posts/main.html' %}

{% block content %}
    {{author}}
<br>
<a href="{% url 'posts:authors_list' %}">Back to Authors List</a>
{% endblock %}

posts/templates/posts/authors_list.html
{% extends 'posts/main.html' %}

{% block content %}
   <ul>
       Lista autorów:
       {% for author in authors %}
            <li><a href="{% url 'posts:author_details' author.id %}">{{author}}</a></li>
       {% endfor %}
   </ul>
{% endblock %}

{% block form %}
  <h2>Dodaj autora</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

posts/templates/posts/main.html
{% extends 'dingo/main.html' %}


       {% block content %}

       {% endblock %}
       {% block form %}

       {% endblock %}

posts/templates/posts/post_details.html
{% extends 'posts/main.html' %}

{% load bootstrap4 %}
<br>
{% block main %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>{{ post.title }}</h2>
      <p>
        <strong>Author:</strong> {{ post.author }}<br>
        <strong>Created:</strong> {{ post.created }}<br>
        <strong>Modified:</strong> {{ post.modified }}<br>
      </p>
      <p>{{ post.content }}</p>
    </div>
    <a href="{% url "posts:posts_list" %}" class="btn btn-primary">Back</a>
  </div>
</div>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'posts/main.html' %}

{% load bootstrap4 %}

{% block main %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>Post List</h2>
      <ul>
        {% for post in posts %}
          <li>
            <a href="{% url 'posts:post_details' post.id %}">
              {{ post.title }} - {{ post.author }} - {{ post.created }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-md-6">
      {% block form %}
      <h2>Add Post</h2>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      {% endblock %}
    </div>
  </div>
</div>
{% endblock %}